### ISSUE TITLE
Service nodes, summary field is not filled in

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_irish_service_catalogue#2]
Looks like only the body field, and not the summary field, is getting populated in the migration.
![Screenshot 2022-06-22 at 10 56 58](https://user-images.githubusercontent.com/2183332/175001418-6f0561ae-122b-43a6-b858-91aa8baac2ae.jpg)

**Comment by alanburke** [comment]
Ok - will have a look

**Comment by alanburke** [comment]
https://github.com/localgovdrupal/localgov_irish_service_catalogue/pull/4
