### ISSUE TITLE
Test nodes are appearing

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_irish_service_catalogue#3]
Some nodes with gibberish titles and some nodes with TEST in title are appearing as part of the migration.
![Screenshot 2022-06-22 at 10 55 18](https://user-images.githubusercontent.com/2183332/175001746-47167913-2df0-4d12-a34f-2d7f859d9b16.jpg)

**Comment by alanburke** [comment]
These are in the source data.
They would need to be removed at source, or a status field added.
